# Generated by Django 5.1.4 on 2025-05-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_pic',
            field=models.ImageField(default='img/avatar/none.bmp', upload_to='img/avatar'),
        ),
    ]
