# Generated by Django 5.1.4 on 2025-05-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingamerating',
            name='picture',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img/gamescreens'),
        ),
        migrations.AlterField(
            model_name='message',
            name='picture',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img/message'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='picture',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img/wishes'),
        ),
    ]
