# Generated by Django 5.1.4 on 2025-05-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_ingamerating_picture_alter_message_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_pic',
            field=models.ImageField(default='static/img/avatar/none.bmp', upload_to='img/avatar'),
        ),
    ]
