# Generated by Django 5.1.4 on 2025-05-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_avatar_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.AddField(
            model_name='user',
            name='status_now',
            field=models.CharField(default='', max_length=20),
        ),
    ]
