# Generated by Django 5.1.4 on 2025-05-03 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_status_user_status_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='my_name',
        ),
    ]
