# Generated by Django 5.1.4 on 2025-05-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_message_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mygroup',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
