# Generated by Django 5.1.4 on 2025-04-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('main_file', models.FileField(upload_to='games/')),
            ],
        ),
    ]
